### ISSUE TITLE
Same issue as #2 Error while pushing this repository to Heroku

### ISSUE THREAD

**Issue by stinkerfly** [serl/ttrss-heroku#9]
Uh-oh! Seemed I got the issue again. Could not execute "git push heroku master" command.
```
  D:\src\ttrss\ttrss-heroku>git push heroku master
Enumerating objects: 92, done.
Counting objects: 100% (92/92), done.
Delta compression using up to 4 threads
Compressing objects: 100% (51/51), done.
Writing objects: 100% (92/92), 40.94 KiB | 6.82 MiB/s, done.
Total 92 (delta 39), reused 92 (delta 39), pack-reused 0
remote: Git submodules detected, installing:
remote: Submodule 'tt-rss' (https://gitlab.com/gothfox/tt-rss.git) registered for path 'tt-rss'
remote: Cloning into 'tt-rss'...
remote: fatal: could not read Username for 'https://gitlab.com': No such device or address
remote: fatal: clone of 'https://gitlab.com/gothfox/tt-rss.git' into submodule path 'tt-rss' failed
remote:
remote: !       Push rejected, submodule install failed
remote:
To https://git.heroku.com/xxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xxx.git'
```
So any solutions?

**Comment by serl** [comment]
I suspect a link with #8. Could you try it?

**Comment by stinkerfly** [comment]
Fixed. But I'm still figuring out why.
Shall I close this issue?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by serl** [comment]
Fixed by itself or with the changed address thanks to #8?

**Comment by stinkerfly** [comment]
Sorry, I did not explain clearly.
I changed the repository address of TTRSS to the official one and deployed to Heroku successfully.

**Comment by serl** [comment]
Fantastic, thanks!
I'll merge the PR and close this issue myself ;)

**Comment by geochemistry** [comment]
> 
> 
> Fixed by itself or with the changed address thanks to #8?

Hey serl, I still have the same issue even after I changed the link in .gitmodule to https://git.tt-rss.org/fox/tt-rss.git

```
$ git push heroku master
Counting objects: 95, done.
Compressing objects: 100% (93/93), done.
Writing objects: 100% (95/95), 32.52 KiB | 2.71 MiB/s, done.
Total 95 (delta 46), reused 0 (delta 0)
remote: Git submodules detected, installing:
remote: Submodule 'tt-rss' (https://git.tt-rss.org/fox/tt-rss.git) registered for path 'tt-rss'
remote: Cloning into 'tt-rss'...
remote: fatal: unable to access 'https://git.tt-rss.org/fox/tt-rss.git/': gnutls_handshake() failed: Handshake failed
remote: fatal: clone of 'https://git.tt-rss.org/fox/tt-rss.git' into submodule path 'tt-rss' failed
remote:
remote: !       Push rejected, submodule install failed
remote:
To https://git.heroku.com/****.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by serl** [comment]
Hello, I'm looking into it.

I may have found a workaround: not using submodules, but downloading the upstream code in `post-install.sh`.
Or maybe I should move it to be done at each boot, with the added benefit of always running the latest version, as Mr Fox itself says to do.

I'll keep you updated.
